import AppBar from '@/components/AppBar';
import './globals.css';
import type { Metadata } from 'next';
import Providers from '@/components/Providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const navItems = [
    { label: 'About', url: '/#about' },
    { label: 'Software', url: '/software' },
    { label: 'Podcast', url: '/podcast' },
    //{ label: 'Blog', url: '/blog' },
    { label: 'Reading', url: '/reading' },
    { label: 'Contact', url: '/#contact' },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <Providers>
                    <AppBar navItems={navItems}></AppBar>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
