import AppBar from '@/components/AppBar';
import './globals.css';
import type { Metadata } from 'next';
import Providers from '@/components/Providers';
import SocialBar from '@/components/SocialBar';
import { MdEmail } from 'react-icons/md';
import { BsGithub, BsInstagram, BsLinkedin, BsSpotify, BsTwitter } from 'react-icons/bs';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const navItems = [
    { label: 'About', url: '/#about' },
    { label: 'Software', url: '/software' },
    { label: 'Podcast', url: '/podcast' },
    //{ label: 'Blog', url: '/blog' },
    { label: 'Reading', url: '/reading' },
    { label: 'Contact', url: '/#contact' },
];

const socials = [
    { link: 'https://open.spotify.com/show/354VSGqhb5Q1KHtNLm03Ub?si=9f83d5bc9d4049b0', icon: <BsSpotify /> },
    { link: 'https://github.com/mattsaxe17', icon: <BsGithub /> },
    { link: 'https://www.linkedin.com/in/mattsaxe17/', icon: <BsLinkedin /> },
    { link: 'https://www.instagram.com/matthew_saxe/', icon: <BsInstagram /> },
    { link: 'https://twitter.com/mattsaxe17', icon: <BsTwitter /> },
    { link: 'mailto:matt@matthewsaxe.com', icon: <MdEmail /> },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' className='dark'>
            <body>
                <Providers>
                    <AppBar navItems={navItems}></AppBar>
                    {children}
                    <SocialBar desktopOnly fixed location='right' socials={socials} />
                </Providers>
            </body>
        </html>
    );
}
